-- Initialize lookup tables

-- Department lookup
INSERT ALL
    INTO DEPARTMENT (D_ID, DEPARTMENT) VALUES (1, 'BenCo')
    INTO DEPARTMENT (D_ID, DEPARTMENT) VALUES (2, 'Computer Science')
    INTO DEPARTMENT (D_ID, DEPARTMENT) VALUES (3, 'Math')
    INTO DEPARTMENT (D_ID, DEPARTMENT) VALUES (4, 'Physics')
    INTO DEPARTMENT (D_ID, DEPARTMENT) VALUES (5, 'Chemistry')
SELECT * FROM DUAL;

-- Title lookup
INSERT ALL
    INTO TITLE (T_ID, TITLE) VALUES (1, 'Department Head')
    INTO TITLE (T_ID, TITLE) VALUES (2, 'Direct Supervisor')
    INTO TITLE (T_ID, TITLE) VALUES (3, 'BenCo')
    INTO TITLE (T_ID, TITLE) VALUES (4, 'Employee')
SELECT * FROM DUAL;

-- Type of document lookup
INSERT ALL
    INTO TYPE_OF_DOCUMENTS (TOD_ID, TYPE_OF_DOC) VALUES (1, '.pdf')
    INTO TYPE_OF_DOCUMENTS (TOD_ID, TYPE_OF_DOC) VALUES (2, '.png')
    INTO TYPE_OF_DOCUMENTS (TOD_ID, TYPE_OF_DOC) VALUES (3, '.jpeg')
    INTO TYPE_OF_DOCUMENTS (TOD_ID, TYPE_OF_DOC) VALUES (4, '.txt')
    INTO TYPE_OF_DOCUMENTS (TOD_ID, TYPE_OF_DOC) VALUES (5, '.doc')
SELECT * FROM DUAL;

-- Type of events lookup
INSERT ALL
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (1, 'University Courses', 80)
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (2, 'Seminars', 60)
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (3, 'Certification Preparation Classes', 75)
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (4, 'Certification', 100)
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (5, 'Technical Training', 90)
    INTO TYPE_OF_EVENTS (TOE_ID, EVENT, PERCENTAGE) VALUES (6, 'Other', 30)
SELECT * FROM DUAL;

-- Commit
COMMIT;